apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pcap-storage
  namespace: neoncore
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
