apiVersion: v1
kind: Service
metadata:
  name: gnb
  namespace: neoncore
spec:
  clusterIP: None
  selector: { app: gnb }
  ports: [{ port: 38412, protocol: SCTP }]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnb
  namespace: neoncore
spec:
  replicas: 1
  selector: { matchLabels: { app: gnb } }
  template:
    metadata: { labels: { app: gnb } }
    spec:
      containers:
        - name: gnb
          image: gradiant/ueransim:3.3.0
          args: ["gnb"]
          env:
            - { name: AMF_HOSTNAME, value: "amf" }
            - { name: MCC, value: "999" }
            - { name: MNC, value: "70" }
            - { name: TAC, value: "1" }
            - { name: SST, value: "1" }
            - { name: SD, value: "1" }
          resources: { requests: { cpu: 20m, memory: 32Mi } }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ue
  namespace: neoncore
spec:
  replicas: 1
  selector: { matchLabels: { app: ue } }
  template:
    metadata: { labels: { app: ue } }
    spec:
      containers:
        - name: ue
          image: gradiant/ueransim:3.3.0
          args: ["ue"]
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - { name: GNB_HOSTNAME, value: "gnb" }
            - { name: MCC, value: "999" }
            - { name: MNC, value: "70" }
            - { name: MSISDN, value: "0000000001" }
            - { name: KEY, value: "465B5CE8B199B49FAA5F0A2EE238A6BC" }
            - { name: OP, value: "E8ED289DEBA952E4283B54E88E6183CA" }
            - { name: OP_TYPE, value: "OPC" }
            - { name: APN, value: "internet" }
            - { name: SST, value: "1" }
            - { name: SD, value: "1" }
          resources: { requests: { cpu: 20m, memory: 32Mi } }
          volumeMounts:
            - { name: dev-tun, mountPath: /dev/net/tun }
      volumes:
        - name: dev-tun
          hostPath: { path: /dev/net/tun, type: CharDevice }
