logger:
  file:
    path: /opt/open5gs/var/log/open5gs/udm.log

udm:
  hnet:
    - id: 1
      scheme: 1
      key: /opt/open5gs/etc/open5gs/hnet/curve25519-1.key
    - id: 2
      scheme: 2
      key: /opt/open5gs/etc/open5gs/hnet/secp256r1-2.key
    - id: 3
      scheme: 1
      key: /opt/open5gs/etc/open5gs/hnet/curve25519-3.key
    - id: 4
      scheme: 2
      key: /opt/open5gs/etc/open5gs/hnet/secp256r1-4.key
    - id: 5
      scheme: 1
      key: /opt/open5gs/etc/open5gs/hnet/curve25519-5.key
    - id: 6
      scheme: 2
      key: /opt/open5gs/etc/open5gs/hnet/secp256r1-6.key
  sbi:
    server:
      - dev: eth0
        port: 7777
    client:
      nrf:
        - uri: http://nrf:7777
  metrics:
    server:
      - dev: eth0
        port: 9090
